<a href="https://colab.research.google.com/github/kailashchaudhary-p/Data-Science-Learning/blob/main/Pandas/chapter%201/Untitled.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
import pandas as pd

In [29]:
s=pd.Series([10,20,30,40,50])
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [30]:
s.dtype
s.index
s.values

array([10, 20, 30, 40, 50])

In [31]:
s.name='numbers'
print(s.name)

numbers

In [32]:
#indexing
s[0]
s[0:1:4]

0    10
Name: numbers, dtype: int64

In [33]:
s[3:0]

Series([], Name: numbers, dtype: int64)

In [34]:
#ilock--> location based index
s.iloc[3]
s.iloc[[1,3,4]]

1    20
3    40
4    50
Name: numbers, dtype: int64

In [35]:
#now we will change our indexing for perr=ticular usage
index=['apple','banana','grapes','orange','mango']
s.index=index

In [37]:
s.loc['apple']

np.int64(10)

In [38]:
s2={
    'apple':0.7,
    'banana':0.6,
    'grapes':3.0,
    'avacado':1.0,
    'mango':0.9,
    'cheeri':0.8,
    'kiwi':1.1,
    'orange':2.5,
    'blackberries':2.3
}
s2

{'apple': 0.7,
 'banana': 0.6,
 'grapes': 3.0,
 'avacado': 1.0,
 'mango': 0.9,
 'cheeri': 0.8,
 'kiwi': 1.1,
 'orange': 2.5,
 'blackberries': 2.3}