<a href="https://colab.research.google.com/github/kailashchaudhary-p/Data-Science-Learning/blob/main/Pandas/chapter%201/Untitled.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
s=pd.Series([10,20,30,40,50])
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [3]:
s.dtype
s.index
s.values

array([10, 20, 30, 40, 50])

In [4]:
s.name='numbers'
print(s.name)

numbers

In [5]:
#indexing
s[0]
s[0:1:4]

0    10
Name: numbers, dtype: int64

In [6]:
s[3:0]

Series([], Name: numbers, dtype: int64)

In [7]:
#ilock--> location based index
s.iloc[3]
s.iloc[[1,3,4]]

1    20
3    40
4    50
Name: numbers, dtype: int64

In [8]:
#now we will change our indexing for perr=ticular usage
index=['apple','banana','grapes','orange','mango']
s.index=index

In [9]:
s.loc['apple']

np.int64(10)

In [10]:
s2={
    'apple':0.7,
    'banana':0.6,
    'grapes':3.0,
    'avacado':1.0,
    'mango':0.9,
    'cheeri':0.8,
    'kiwi':1.1,
    'orange':2.5,
    'blackberries':2.3
}
s2

{'apple': 0.7,
 'banana': 0.6,
 'grapes': 3.0,
 'avacado': 1.0,
 'mango': 0.9,
 'cheeri': 0.8,
 'kiwi': 1.1,
 'orange': 2.5,
 'blackberries': 2.3}

In [11]:
s2=pd.Series(s2)
s2

apple           0.7
banana          0.6
grapes          3.0
avacado         1.0
mango           0.9
cheeri          0.8
kiwi            1.1
orange          2.5
blackberries    2.3
dtype: float64

In [12]:
print(type(s2))

<class 'pandas.core.series.Series'>

In [13]:
s2.unique()

array([0.7, 0.6, 3. , 1. , 0.9, 0.8, 1.1, 2.5, 2.3])

In [14]:
s2.count()

np.int64(9)