<a href="https://colab.research.google.com/github/kailashchaudhary-p/Data-Science-Learning/blob/main/Pandas/chapter%201/Untitled.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [3]:
s=pd.Series([10,20,30,40,50])
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [4]:
s.dtype
s.index
s.values

array([10, 20, 30, 40, 50])

In [5]:
s.name='numbers'
print(s.name)

numbers

In [6]:
#indexing
s[0]
s[0:1:4]

0    10
Name: numbers, dtype: int64

In [7]:
s[3:0]

Series([], Name: numbers, dtype: int64)

In [8]:
#ilock--> location based index
s.iloc[3]
s.iloc[[1,3,4]]

1    20
3    40
4    50
Name: numbers, dtype: int64

In [9]:
#now we will change our indexing for perr=ticular usage
index=['apple','banana','grapes','orange','mango']
s.index=index

In [10]:
s.loc['apple']

np.int64(10)

In [11]:
s2={
    'apple':0.7,
    'banana':0.6,
    'grapes':3.0,
    'avacado':1.0,
    'mango':0.9,
    'cheeri':0.8,
    'kiwi':1.1,
    'orange':2.5,
    'blackberries':2.3
}
s2

{'apple': 0.7,
 'banana': 0.6,
 'grapes': 3.0,
 'avacado': 1.0,
 'mango': 0.9,
 'cheeri': 0.8,
 'kiwi': 1.1,
 'orange': 2.5,
 'blackberries': 2.3}

In [12]:
s2=pd.Series(s2)
s2

apple           0.7
banana          0.6
grapes          3.0
avacado         1.0
mango           0.9
cheeri          0.8
kiwi            1.1
orange          2.5
blackberries    2.3
dtype: float64

In [13]:
print(type(s2))

<class 'pandas.core.series.Series'>

In [14]:
s2.unique()

array([0.7, 0.6, 3. , 1. , 0.9, 0.8, 1.1, 2.5, 2.3])

In [15]:
s2.count()

np.int64(9)

In [16]:
s2.describe()

count    9.000000
mean     1.433333
std      0.905539
min      0.600000
25%      0.800000
50%      1.000000
75%      2.300000
max      3.000000
dtype: float64

In [17]:
#Logic oprator

In [18]:
#Data Frame (df)
data={
    'name':['kailash','ajay','aman','alice','bob','charlie'],
    'age':[20,25,30,35,19,22],
    'Department':['IT','HR','Finance','IT','HR','Finance'],
    'salary':[50000,60000,40000,250000,300000,80000]
}
data

{'name': ['kailash', 'ajay', 'aman', 'alice', 'bob', 'charlie'],
 'age': [20, 25, 30, 35, 19, 22],
 'Department': ['IT', 'HR', 'Finance', 'IT', 'HR', 'Finance'],
 'salary': [50000, 60000, 40000, 250000, 300000, 80000]}

In [19]:
df=pd.DataFrame(data)

In [20]:
df

      name  age Department  salary
0  kailash   20         IT   50000
1     ajay   25         HR   60000
2     aman   30    Finance   40000
3    alice   35         IT  250000
4      bob   19         HR  300000
5  charlie   22    Finance   80000

In [21]:
df.head(2)

      name  age Department  salary
0  kailash   20         IT   50000
1     ajay   25         HR   60000

In [22]:
df.tail(5)

      name  age Department  salary
1     ajay   25         HR   60000
2     aman   30    Finance   40000
3    alice   35         IT  250000
4      bob   19         HR  300000
5  charlie   22    Finance   80000

In [23]:
#loc&iloc in df

In [24]:
df.loc[1:3]

    name  age Department  salary
1   ajay   25         HR   60000
2   aman   30    Finance   40000
3  alice   35         IT  250000

In [25]:
df.iloc[1:3,[1,3
             ]]

   age  salary
1   25   60000
2   30   40000

In [26]:
#the direct indexing is in data frame or series is very comlex thats why we will use loc or iloc

In [27]:
#to se perticuler column or multiple
df.age

0    20
1    25
2    30
3    35
4    19
5    22
Name: age, dtype: int64

In [28]:
df['age']

0    20
1    25
2    30
3    35
4    19
5    22
Name: age, dtype: int64

In [29]:
df['age'].unique(

)

array([20, 25, 30, 35, 19, 22])

In [30]:
df.describe()

             age         salary
count   6.000000       6.000000
mean   25.166667  130000.000000
std     6.242329  114192.819389
min    19.000000   40000.000000
25%    20.500000   52500.000000
50%    23.500000   70000.000000
75%    28.750000  207500.000000
max    35.000000  300000.000000

In [31]:
df.rename(columns={'name':'Name'},inplace=True)

In [32]:
df

      Name  age Department  salary
0  kailash   20         IT   50000
1     ajay   25         HR   60000
2     aman   30    Finance   40000
3    alice   35         IT  250000
4      bob   19         HR  300000
5  charlie   22    Finance   80000

In [33]:
#broadcasting in pandas
df['salary']=df['salary']+5000

In [34]:
df

      Name  age Department  salary
0  kailash   20         IT   55000
1     ajay   25         HR   65000
2     aman   30    Finance   45000
3    alice   35         IT  255000
4      bob   19         HR  305000
5  charlie   22    Finance   85000

In [35]:
df.drop(columns=['salary'],inplace=True)

In [36]:
import numpy as np
dataset={
    'name':['kailash','ajay',np.nan,'aman','alice','bob',np.nan,'charlie',np.nan],
    'urn':[789,123,456,741,np.nan,963,852,np.nan,951],
    'project':['banking app','task managment','clone spotify','card managment',np.nan,'player','xyz','abc','k']
}
df2=pd.DataFrame(dataset)

In [37]:
df2

      name    urn         project
0  kailash  789.0     banking app
1     ajay  123.0  task managment
2      NaN  456.0   clone spotify
3     aman  741.0  card managment
4    alice    NaN             NaN
5      bob  963.0          player
6      NaN  852.0             xyz
7  charlie    NaN             abc
8      NaN  951.0               k

In [38]:
#now this is our prectice set in this we work on df2 data opration and we clean the data
df2.isnull().sum()

name       3
urn        2
project    1
dtype: int64

In [39]:
df2.dropna()

      name    urn         project
0  kailash  789.0     banking app
1     ajay  123.0  task managment
3     aman  741.0  card managment
5      bob  963.0          player

In [40]:
df2.dropna(how='all')

      name    urn         project
0  kailash  789.0     banking app
1     ajay  123.0  task managment
2      NaN  456.0   clone spotify
3     aman  741.0  card managment
4    alice    NaN             NaN
5      bob  963.0          player
6      NaN  852.0             xyz
7  charlie    NaN             abc
8      NaN  951.0               k

In [41]:
df2.dropna(how='any')

      name    urn         project
0  kailash  789.0     banking app
1     ajay  123.0  task managment
3     aman  741.0  card managment
5      bob  963.0          player

In [42]:
#this the other way fill the null values
df2.fillna(5)

      name    urn         project
0  kailash  789.0     banking app
1     ajay  123.0  task managment
2        5  456.0   clone spotify
3     aman  741.0  card managment
4    alice    5.0               5
5      bob  963.0          player
6        5  852.0             xyz
7  charlie    5.0             abc
8        5  951.0               k

In [43]:
df

      Name  age Department
0  kailash   20         IT
1     ajay   25         HR
2     aman   30    Finance
3    alice   35         IT
4      bob   19         HR
5  charlie   22    Finance

In [44]:
df2

      name    urn         project
0  kailash  789.0     banking app
1     ajay  123.0  task managment
2      NaN  456.0   clone spotify
3     aman  741.0  card managment
4    alice    NaN             NaN
5      bob  963.0          player
6      NaN  852.0             xyz
7  charlie    NaN             abc
8      NaN  951.0               k

In [45]:
df2['urn'].fillna(df2['urn'].median())

0    789.0
1    123.0
2    456.0
3    741.0
4    789.0
5    963.0
6    852.0
7    789.0
8    951.0
Name: urn, dtype: float64

In [46]:
#now we will know about the forward fill & backword fill
#the forword fill is top to bottum & the backword fill is bottom to top
df2['urn'].fillna(method='ffill')

/tmp/ipykernel_3043/880483959.py:3: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df2['urn'].fillna(method='ffill')

0    789.0
1    123.0
2    456.0
3    741.0
4    741.0
5    963.0
6    852.0
7    852.0
8    951.0
Name: urn, dtype: float64

In [47]:
df2['urn'].fillna(method='bfill')

/tmp/ipykernel_3043/489831362.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df2['urn'].fillna(method='bfill')

0    789.0
1    123.0
2    456.0
3    741.0
4    963.0
5    963.0
6    852.0
7    951.0
8    951.0
Name: urn, dtype: float64

In [48]:
#now we will replace the value
df2['name']=df2['name'].replace('kailash','harsh')
df2

      name    urn         project
0    harsh  789.0     banking app
1     ajay  123.0  task managment
2      NaN  456.0   clone spotify
3     aman  741.0  card managment
4    alice    NaN             NaN
5      bob  963.0          player
6      NaN  852.0             xyz
7  charlie    NaN             abc
8      NaN  951.0               k

In [49]:
df2

      name    urn         project
0    harsh  789.0     banking app
1     ajay  123.0  task managment
2      NaN  456.0   clone spotify
3     aman  741.0  card managment
4    alice    NaN             NaN
5      bob  963.0          player
6      NaN  852.0             xyz
7  charlie    NaN             abc
8      NaN  951.0               k

In [50]:
#now we will deal with duplicate values
df_dup=df2.duplicated()
df_dup

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
dtype: bool

In [51]:
#now we will learn about the lamda function in pandasdf
df2['name_upper'] = df2['name'].apply(lambda x: x.upper() if pd.notna(x) else x)
df2

      name    urn         project name_upper
0    harsh  789.0     banking app      HARSH
1     ajay  123.0  task managment       AJAY
2      NaN  456.0   clone spotify        NaN
3     aman  741.0  card managment       AMAN
4    alice    NaN             NaN      ALICE
5      bob  963.0          player        BOB
6      NaN  852.0             xyz        NaN
7  charlie    NaN             abc    CHARLIE
8      NaN  951.0               k        NaN

In [52]:
#join & mearg
Department_info={
    'department_id':[1,2,3,4],
    'department_name':['IT','HR','Finance','Marketing'],
}
df3=pd.DataFrame(Department_info)
df3

   department_id department_name
0              1              IT
1              2              HR
2              3         Finance
3              4       Marketing

In [53]:
#concat data frame
pd.concat([df2,df3,df])

,name,urn,project,name_upper,department_id,department_name,Name,age,Department
0,harsh,789.0,banking app,HARSH,NaN,NaN,NaN,NaN,NaN
1,ajay,123.0,task managment,AJAY,NaN,NaN,NaN,NaN,NaN
2,NaN,456.0,clone spotify,NaN,NaN,NaN,NaN,NaN,NaN
3,aman,741.0,card managment,AMAN,NaN,NaN,NaN,NaN,NaN
4,alice,NaN,NaN,ALICE,NaN,NaN,NaN,NaN,NaN
5,bob,963.0,player,BOB,NaN,NaN,NaN,NaN,NaN
6,NaN,852.0,xyz,NaN,NaN,NaN,NaN,NaN,NaN
7,charlie,NaN,abc,CHARLIE,NaN,NaN,NaN,NaN,NaN
8,NaN,951.0,k,NaN,NaN,NaN,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,1.0,IT,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,2.0,HR,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,3.0,Finance,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,4.0,Marketing,NaN,NaN,NaN
0,NaN,NaN,NaN,NaN,NaN,NaN,kailash,20.0,IT
1,NaN,NaN,NaN,NaN,NaN,NaN,ajay,25.0,HR
2,NaN,NaN,NaN,NaN,NaN,NaN,aman,30.0,Finance
3,NaN,NaN,NaN,NaN,NaN,NaN,alice,35.0,IT
4,NaN,NaN,NaN,NaN,NaN,NaN,bob,19.0,HR
5,NaN,NaN,NaN,NaN,NaN,NaN,charlie,22.0,Finance

In [54]:
pd.concat([df2,df3,df],axis=1)

,name,urn,project,name_upper,department_id,department_name,Name,age,Department
0,harsh,789.0,banking app,HARSH,1.0,IT,kailash,20.0,IT
1,ajay,123.0,task managment,AJAY,2.0,HR,ajay,25.0,HR
2,NaN,456.0,clone spotify,NaN,3.0,Finance,aman,30.0,Finance
3,aman,741.0,card managment,AMAN,4.0,Marketing,alice,35.0,IT
4,alice,NaN,NaN,ALICE,NaN,NaN,bob,19.0,HR
5,bob,963.0,player,BOB,NaN,NaN,charlie,22.0,Finance
6,NaN,852.0,xyz,NaN,NaN,NaN,NaN,NaN,NaN
7,charlie,NaN,abc,CHARLIE,NaN,NaN,NaN,NaN,NaN
8,NaN,951.0,k,NaN,NaN,NaN,NaN,NaN,NaN

In [56]:
#now the next step is work on real data and we will cleaning tahe data the null values & invalid values
data = pd.read_csv('/content/customers-1000.csv')
data

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,dE014d010c7ab0c,Andrew,Goodman,Stewart-Flynn,Rowlandberg,Macao,846-790-4623x4715,(422)787-2331x71127,marieyates@gomez-spencer.info,2021-07-26,http://www.shea.biz/
1,2,2B54172c8b65eC3,Alvin,Lane,"Terry, Proctor and Lawrence",Bethside,Papua New Guinea,124-597-8652x05682,321.441.0588x6218,alexandra86@mccoy.com,2021-06-24,http://www.pena-cole.com/
2,3,d794Dd48988d2ac,Jenna,Harding,Bailey Group,Moniquemouth,China,(335)987-3085x3780,001-680-204-8312,justincurtis@pierce.org,2020-04-05,http://www.booth-reese.biz/
3,4,3b3Aa4aCc68f3Be,Fernando,Ford,Moss-Maxwell,Leeborough,Macao,(047)752-3122,048.779.5035x9122,adeleon@hubbard.org,2020-11-29,http://www.hebert.com/
4,5,D60df62ad2ae41E,Kara,Woods,Mccarthy-Kelley,Port Jacksonland,Nepal,+1-360-693-4419x19272,163-627-2565,jesus90@roberson.info,2022-04-22,http://merritt.com/
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,FbcCaF483aFaFAE,Diana,Monroe,Bass-Wilson,Lake Jacksonmouth,Guatemala,+1-171-715-9766x54993,(489)413-7296x32807,cassidymercado@bonilla.com,2022-01-09,http://castro.net/
996,997,979c4D58Ae9a9cc,Jerry,Morales,Pratt-King,South Dominiquemouth,Georgia,132.253.8501x097,+1-301-292-8363x80270,gavin13@logan-downs.com,2021-08-21,https://www.braun.info/
997,998,D0DcF6a4BcefCc8,Tracie,Floyd,"Holt, Wilson and Shields",East Chloeshire,Solomon Islands,1193982387,(482)926-8966,lowehailey@oconnor.org,2020-04-22,http://www.zavala-rubio.com/
998,999,90EE9CbbDa374E9,Paul,Barnes,"Brown, Oliver and Haynes",South Shane,Finland,+1-537-466-3245x3699,791-835-9075,hodgeseddie@hardin-wells.com,2021-03-12,https://stone-randolph.info/
999,1000,51732B5b2328015,Dominic,Duran,Durham LLC,East Wendy,British Indian Ocean Territory (Chagos Archipe...,+1-278-758-4331,814-860-0941x057,owarner@velasquez.info,2021-12-09,http://www.cox.com/

In [57]:
data .info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Index              1000 non-null   int64
 1   Customer Id        1000 non-null   object
 2   First Name         1000 non-null   object
 3   Last Name          1000 non-null   object
 4   Company            1000 non-null   object
 5   City               1000 non-null   object
 6   Country            1000 non-null   object
 7   Phone 1            1000 non-null   object
 8   Phone 2            1000 non-null   object
 9   Email              1000 non-null   object
 10  Subscription Date  1000 non-null   object
 11  Website            1000 non-null   object
dtypes: int64(1), object(11)
memory usage: 93.9+ KB