<a href="https://colab.research.google.com/github/kailashchaudhary-p/Data-Science-Learning/blob/main/Pandas/chapter%201/Untitled.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [5]:
s=pd.Series([10,20,30,40,50])
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [6]:
s.dtype
s.index
s.values

array([10, 20, 30, 40, 50])

In [7]:
s.name='numbers'
print(s.name)

numbers

In [8]:
#indexing
s[0]
s[0:1:4]

0    10
Name: numbers, dtype: int64

In [10]:
s[3:0]

Series([], Name: numbers, dtype: int64)

In [11]:
#ilock--> location based index
s.iloc[3]
s.iloc[[1,3,4]]

1    20
3    40
4    50
Name: numbers, dtype: int64

In [12]:
#now we will change our indexing for perr=ticular usage
index=['apple','banana','grapes','orange','mango']
s.index=index

In [13]:
s.['apple']

SyntaxError: invalid syntax (2856270915.py, line 1)